spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Local
    url: jdbc:mysql://localhost:3306/sidequestdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: thrmEkel123!

#     RDS
#    url: jdbc:mysql://sidequestdb.cinzzb9ewscr.ap-northeast-2.rds.amazonaws.com:3306/sidequestdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ${SIDEQUEST_RDS_USERNAME}
#    password: ${SIDEQUEST_RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  springfox:
    documentation:
      swagger-ui:
        host: localhost:8080
#JWT
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${SIDEQUEST_JWT_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

#img-test
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: sidequest-bucket
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2

#server:
#  port: 8090